# Generated by Django 6.0.3 on 2026-04-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_job_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeprofile',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='cgpa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='languages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='experience',
            field=models.TextField(blank=True),
        ),
    ]
