# Generated by Django 6.0.3 on 2026-04-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_resumeprofile_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
